<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use App\Models\Customer;
use App\Models\Vessel;
use App\Models\Quote;
use App\Models\QuoteItem;
use App\Models\User;
use App\Models\Currency;

class DemoDataSeeder extends Seeder
{
    public function run(): void
    {
        // Disable foreign key checks
        Schema::disableForeignKeyConstraints();

        // Truncate tables
        $tables = [
            'contract_deliveries',
            'contract_attachments',
            'contracts',
            'sales_order_items',
            'sales_orders',
            'quote_items',
            'quotes',
            'vessels',
            'customers',
            'follow_ups',
            'activity_logs',
            'contract_sequences',
            'quote_sequences',
            'sales_order_sequences',
        ];

        foreach ($tables as $table) {
             if (Schema::hasTable($table)) {
                DB::table($table)->truncate();
             }
        }

        Schema::enableForeignKeyConstraints();

        // Get a user to be the creator
        $user = User::first();
        if (!$user) {
             $user = User::factory()->create([
                 'name' => 'Admin User',
                 'email' => 'admin@example.com',
             ]);
        }

        // Ensure we have a currency
        $currencyCode = config('company.default_code', 'EUR');
        $currency = Currency::where('code', $currencyCode)->first();
        if (!$currency) {
             $currency = Currency::first() ?? Currency::factory()->create(['code' => 'EUR', 'symbol' => '€']);
        }

        // Create 5 Customers
        $customers = Customer::factory()->count(5)->create([
            'created_by' => $user->id,
        ]);

        foreach ($customers as $customer) {
            // Create 1-3 Vessels for each customer
            $vessels = Vessel::factory()->count(rand(1, 3))->create([
                'customer_id' => $customer->id,
                'created_by' => $user->id,
            ]);

            foreach ($vessels as $vessel) {
                // Create 1-2 Quotes for each vessel
                $quotes = Quote::factory()->count(rand(1, 2))->create([
                    'customer_id' => $customer->id,
                    'vessel_id' => $vessel->id,
                    'currency_id' => $currency->id,
                    'currency' => $currency->code,
                    'created_by' => $user->id,
                    'status' => 'draft',
                    'quote_no' => null, // Will be generated by boot logic since we truncated sequences
                ]);

                foreach ($quotes as $quote) {
                    // Create items
                    for ($i = 0; $i < rand(2, 5); $i++) {
                        QuoteItem::create([
                            'quote_id' => $quote->id,
                            'sort_order' => $i,
                            'section' => 'Main',
                            'item_type' => 'service',
                            'description' => 'Demo Service Item ' . ($i + 1),
                            'qty' => rand(1, 10),
                            'unit' => 'pcs',
                            'unit_price' => rand(100, 1000),
                            'discount_amount' => 0,
                            'vat_rate' => 20,
                            'is_optional' => false,
                        ]);
                    }
                    $quote->recalculateTotals();
                }
            }
        }
    }
}
